apiVersion: v1
kind: Service
metadata:
  name: {{ ( include "webhook-instrumentor.name" . ) }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: 443
      targetPort: webhook-api