
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: r
  name: testserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      annotations:
        test: testval
      labels:
        app: testserver
        appdApp: MD-instr-wh
        appdInstr: do
        language: nodejs
    spec:
      containers:
      - name: testserver
        image: chrlic/sample-nodejs-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  namespace: r
  name: testserver
  labels:
    run: testserver
spec:
  ports:
  - port: 8585
    targetPort: 8000
    protocol: TCP
  selector:
    app: testserver
  type: LoadBalancer
